#!/bin/bash
set -o errexit
set -o errtrace
set -o pipefail
set -o nounset

[ -d hotspot/test ] || tar xf hotspot.tar.xz hotspot/test/

debian/tests/jtreg-autopkgtest.sh -dir:hotspot/test compiler gc runtime sanity serviceability
debian/tests/jtdiff-autopkgtest.sh hotspot
